import { AIProvider, IncidentAnalysisInput, IncidentAnalysis } from "./types";

export class GeminiAIProvider implements AIProvider {
  private apiKey: string | undefined;
  private model: string;

  constructor(apiKey?: string, model = "gemini-2.0-flash") {
    this.apiKey = apiKey || process.env.GEMINI_API_KEY;
    this.model = model;
  }

  isConfigured(): boolean {
    return !!this.apiKey && this.apiKey.trim().length > 0;
  }

  async analyzeIncident(input: IncidentAnalysisInput): Promise<IncidentAnalysis> {
    if (!this.isConfigured()) {
      throw new Error("Gemini API key is not configured");
    }

    const prompt = this.buildPrompt(input);
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${this.model}:generateContent?key=${this.apiKey}`;

    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: prompt }],
          },
        ],
        generationConfig: {
          responseMimeType: "application/json",
          temperature: 0.2,
        },
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API returned error HTTP ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!candidateText) {
      throw new Error("No response generated by Gemini model");
    }

    try {
      const parsed = JSON.parse(candidateText);
      return {
        provider: "gemini",
        model: this.model,
        likelyCause: parsed.likelyCause || "Undetermined root cause based on available signals",
        confidence: Math.min(100, Math.max(0, parsed.confidence ?? 80)),
        evidence: Array.isArray(parsed.evidence) ? parsed.evidence : [],
        recommendedActions: Array.isArray(parsed.recommendedActions) ? parsed.recommendedActions : [],
        isAiConfigured: true,
        analyzedAt: Date.now(),
      };
    } catch {
      throw new Error("Failed to parse structured JSON from Gemini analysis response");
    }
  }

  private buildPrompt(input: IncidentAnalysisInput): string {
    const deploymentInfo = input.recentDeployment
      ? `Recent Deployment:
- Version: ${input.recentDeployment.version} (Commit: ${input.recentDeployment.commitHash})
- Message: "${input.recentDeployment.commitMessage || "No commit message"}"
- Deployed at: ${new Date(input.recentDeployment.deployedAt).toISOString()} by ${input.recentDeployment.deployedBy}`
      : "Recent Deployment: None detected within correlation window";

    const metricsSummary = input.metrics.length > 0
      ? input.metrics.map((m) => `- ${m.name}: ${m.value} ${m.unit || ""} (Delta: ${m.deltaPercent ? (m.deltaPercent > 0 ? "+" : "") + m.deltaPercent + "%" : "N/A"})`).join("\n")
      : "No metric anomalies recorded";

    const logsSummary = input.relatedLogs.length > 0
      ? input.relatedLogs.slice(0, 10).map((l) => `[${l.level.toUpperCase()}] ${l.message} (Attributes: ${JSON.stringify(l.attributes || {})})`).join("\n")
      : "No related error logs found";

    const tracesSummary = input.relatedTraces.length > 0
      ? input.relatedTraces.slice(0, 10).map((t) => `- ${t.rootSpanName} (${t.durationMs}ms, status: ${t.statusCode})${t.errorSpans ? ` [Errors in spans: ${t.errorSpans.join(", ")}]` : ""}`).join("\n")
      : "No slow or failed traces found";

    return `You are RadarFlow AI, a principal site reliability engineer and distributed systems expert.
Analyze the following structured incident telemetry and determine the likely root cause, evidence points, and concrete actionable investigation steps.

Respond strictly in JSON format matching this exact schema:
{
  "likelyCause": "A concise 1-2 sentence explanation of the most probable technical cause",
  "confidence": 85, // Integer percentage between 0 and 100
  "evidence": [
    "Concrete observation from telemetry supporting this conclusion",
    "Second concrete piece of evidence"
  ],
  "recommendedActions": [
    "Specific immediate mitigation or investigation step 1",
    "Specific step 2"
  ]
}

INCIDENT CONTEXT:
Title: ${input.incidentTitle}
Service: ${input.service}
Environment: ${input.environment}
Severity: ${input.severity}
Trigger Reason: ${input.triggerReason}
First Detected: ${new Date(input.firstDetectedAt).toISOString()}

${deploymentInfo}

METRICS AT INCIDENT TRIGGER:
${metricsSummary}

RELATED ERROR LOGS:
${logsSummary}

RELATED SLOW / FAILED TRACES:
${tracesSummary}
`;
  }
}
